//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceTestMachine.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebServiceTestMachine.ServiceReference1.HelloWorldResponse HelloWorld(WebServiceTestMachine.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name SanmarTestSericeResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SanmarTestSerice", ReplyAction="*")]
        WebServiceTestMachine.ServiceReference1.SanmarTestSericeResponse SanmarTestSerice(WebServiceTestMachine.ServiceReference1.SanmarTestSericeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/loadExistingAppoint", ReplyAction="*")]
        void loadExistingAppoint();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceTestMachine.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebServiceTestMachine.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceTestMachine.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebServiceTestMachine.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SanmarTestSericeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SanmarTestSerice", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceTestMachine.ServiceReference1.SanmarTestSericeRequestBody Body;
        
        public SanmarTestSericeRequest() {
        }
        
        public SanmarTestSericeRequest(WebServiceTestMachine.ServiceReference1.SanmarTestSericeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SanmarTestSericeRequestBody {
        
        public SanmarTestSericeRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SanmarTestSericeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SanmarTestSericeResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceTestMachine.ServiceReference1.SanmarTestSericeResponseBody Body;
        
        public SanmarTestSericeResponse() {
        }
        
        public SanmarTestSericeResponse(WebServiceTestMachine.ServiceReference1.SanmarTestSericeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SanmarTestSericeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SanmarTestSericeResult;
        
        public SanmarTestSericeResponseBody() {
        }
        
        public SanmarTestSericeResponseBody(string SanmarTestSericeResult) {
            this.SanmarTestSericeResult = SanmarTestSericeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : WebServiceTestMachine.ServiceReference1.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<WebServiceTestMachine.ServiceReference1.Service1Soap>, WebServiceTestMachine.ServiceReference1.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceTestMachine.ServiceReference1.HelloWorldResponse WebServiceTestMachine.ServiceReference1.Service1Soap.HelloWorld(WebServiceTestMachine.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebServiceTestMachine.ServiceReference1.HelloWorldRequest inValue = new WebServiceTestMachine.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebServiceTestMachine.ServiceReference1.HelloWorldRequestBody();
            WebServiceTestMachine.ServiceReference1.HelloWorldResponse retVal = ((WebServiceTestMachine.ServiceReference1.Service1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceTestMachine.ServiceReference1.SanmarTestSericeResponse WebServiceTestMachine.ServiceReference1.Service1Soap.SanmarTestSerice(WebServiceTestMachine.ServiceReference1.SanmarTestSericeRequest request) {
            return base.Channel.SanmarTestSerice(request);
        }
        
        public string SanmarTestSerice() {
            WebServiceTestMachine.ServiceReference1.SanmarTestSericeRequest inValue = new WebServiceTestMachine.ServiceReference1.SanmarTestSericeRequest();
            inValue.Body = new WebServiceTestMachine.ServiceReference1.SanmarTestSericeRequestBody();
            WebServiceTestMachine.ServiceReference1.SanmarTestSericeResponse retVal = ((WebServiceTestMachine.ServiceReference1.Service1Soap)(this)).SanmarTestSerice(inValue);
            return retVal.Body.SanmarTestSericeResult;
        }
        
        public void loadExistingAppoint() {
            base.Channel.loadExistingAppoint();
        }
    }
}
