//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("VisitorAPPModel", "FK_InfoUser_TypeUserRole", "TypeUserRole", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VisitorAppointmentDB.TypeUserRole), "InfoUser", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VisitorAppointmentDB.InfoUser), true)]
[assembly: EdmRelationshipAttribute("VisitorAPPModel", "FK_InfoUserFrom_InfoMessage", "InfoUser", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VisitorAppointmentDB.InfoUser), "InfoMessage", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VisitorAppointmentDB.InfoMessage), true)]
[assembly: EdmRelationshipAttribute("VisitorAPPModel", "FK_InfoUserTo_InfoMessage", "InfoUser", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VisitorAppointmentDB.InfoUser), "InfoMessage", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VisitorAppointmentDB.InfoMessage), true)]
[assembly: EdmRelationshipAttribute("VisitorAPPModel", "FK_TypeMsgContent_InfoMessage", "TypeMsgContent", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VisitorAppointmentDB.TypeMsgContent), "InfoMessage", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VisitorAppointmentDB.InfoMessage), true)]
[assembly: EdmRelationshipAttribute("VisitorAPPModel", "FK_TypeMsgStatus_msgStatus", "TypeMsgStatu", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VisitorAppointmentDB.TypeMsgStatu), "InfoMessage", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VisitorAppointmentDB.InfoMessage), true)]

#endregion

namespace VisitorAppointmentDB
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class VisitorAPPEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new VisitorAPPEntities object using the connection string found in the 'VisitorAPPEntities' section of the application configuration file.
        /// </summary>
        public VisitorAPPEntities() : base("name=VisitorAPPEntities", "VisitorAPPEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new VisitorAPPEntities object.
        /// </summary>
        public VisitorAPPEntities(string connectionString) : base(connectionString, "VisitorAPPEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new VisitorAPPEntities object.
        /// </summary>
        public VisitorAPPEntities(EntityConnection connection) : base(connection, "VisitorAPPEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<InfoUser> InfoUsers
        {
            get
            {
                if ((_InfoUsers == null))
                {
                    _InfoUsers = base.CreateObjectSet<InfoUser>("InfoUsers");
                }
                return _InfoUsers;
            }
        }
        private ObjectSet<InfoUser> _InfoUsers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TypeMsgContent> TypeMsgContents
        {
            get
            {
                if ((_TypeMsgContents == null))
                {
                    _TypeMsgContents = base.CreateObjectSet<TypeMsgContent>("TypeMsgContents");
                }
                return _TypeMsgContents;
            }
        }
        private ObjectSet<TypeMsgContent> _TypeMsgContents;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TypeMsgStatu> TypeMsgStatus
        {
            get
            {
                if ((_TypeMsgStatus == null))
                {
                    _TypeMsgStatus = base.CreateObjectSet<TypeMsgStatu>("TypeMsgStatus");
                }
                return _TypeMsgStatus;
            }
        }
        private ObjectSet<TypeMsgStatu> _TypeMsgStatus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TypeUserRole> TypeUserRoles
        {
            get
            {
                if ((_TypeUserRoles == null))
                {
                    _TypeUserRoles = base.CreateObjectSet<TypeUserRole>("TypeUserRoles");
                }
                return _TypeUserRoles;
            }
        }
        private ObjectSet<TypeUserRole> _TypeUserRoles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<InfoMessage> InfoMessages
        {
            get
            {
                if ((_InfoMessages == null))
                {
                    _InfoMessages = base.CreateObjectSet<InfoMessage>("InfoMessages");
                }
                return _InfoMessages;
            }
        }
        private ObjectSet<InfoMessage> _InfoMessages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BadgeDetail> BadgeDetails
        {
            get
            {
                if ((_BadgeDetails == null))
                {
                    _BadgeDetails = base.CreateObjectSet<BadgeDetail>("BadgeDetails");
                }
                return _BadgeDetails;
            }
        }
        private ObjectSet<BadgeDetail> _BadgeDetails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SettingsForm> SettingsForms
        {
            get
            {
                if ((_SettingsForms == null))
                {
                    _SettingsForms = base.CreateObjectSet<SettingsForm>("SettingsForms");
                }
                return _SettingsForms;
            }
        }
        private ObjectSet<SettingsForm> _SettingsForms;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the InfoUsers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInfoUsers(InfoUser infoUser)
        {
            base.AddObject("InfoUsers", infoUser);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TypeMsgContents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTypeMsgContents(TypeMsgContent typeMsgContent)
        {
            base.AddObject("TypeMsgContents", typeMsgContent);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TypeMsgStatus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTypeMsgStatus(TypeMsgStatu typeMsgStatu)
        {
            base.AddObject("TypeMsgStatus", typeMsgStatu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TypeUserRoles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTypeUserRoles(TypeUserRole typeUserRole)
        {
            base.AddObject("TypeUserRoles", typeUserRole);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the InfoMessages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInfoMessages(InfoMessage infoMessage)
        {
            base.AddObject("InfoMessages", infoMessage);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BadgeDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBadgeDetails(BadgeDetail badgeDetail)
        {
            base.AddObject("BadgeDetails", badgeDetail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SettingsForms EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSettingsForms(SettingsForm settingsForm)
        {
            base.AddObject("SettingsForms", settingsForm);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VisitorAPPModel", Name="BadgeDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BadgeDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BadgeDetail object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static BadgeDetail CreateBadgeDetail(global::System.Int32 id)
        {
            BadgeDetail badgeDetail = new BadgeDetail();
            badgeDetail.Id = id;
            return badgeDetail;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private Nullable<global::System.Int32> _UserID;
        partial void OnUserIDChanging(Nullable<global::System.Int32> value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastOpenTime
        {
            get
            {
                return _LastOpenTime;
            }
            set
            {
                OnLastOpenTimeChanging(value);
                ReportPropertyChanging("LastOpenTime");
                _LastOpenTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastOpenTime");
                OnLastOpenTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastOpenTime;
        partial void OnLastOpenTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnLastOpenTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastCloseTime
        {
            get
            {
                return _LastCloseTime;
            }
            set
            {
                OnLastCloseTimeChanging(value);
                ReportPropertyChanging("LastCloseTime");
                _LastCloseTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastCloseTime");
                OnLastCloseTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastCloseTime;
        partial void OnLastCloseTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnLastCloseTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BadgeCount
        {
            get
            {
                return _BadgeCount;
            }
            set
            {
                OnBadgeCountChanging(value);
                ReportPropertyChanging("BadgeCount");
                _BadgeCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BadgeCount");
                OnBadgeCountChanged();
            }
        }
        private Nullable<global::System.Int32> _BadgeCount;
        partial void OnBadgeCountChanging(Nullable<global::System.Int32> value);
        partial void OnBadgeCountChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VisitorAPPModel", Name="InfoMessage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class InfoMessage : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new InfoMessage object.
        /// </summary>
        /// <param name="msgID">Initial value of the msgID property.</param>
        /// <param name="fromUserID">Initial value of the FromUserID property.</param>
        /// <param name="toUserID">Initial value of the ToUserID property.</param>
        /// <param name="createdDateTime">Initial value of the CreatedDateTime property.</param>
        /// <param name="msgTypeID">Initial value of the msgTypeID property.</param>
        /// <param name="visitorName">Initial value of the VisitorName property.</param>
        /// <param name="isUrgent">Initial value of the isUrgent property.</param>
        /// <param name="msgStatusID">Initial value of the msgStatusID property.</param>
        /// <param name="isActive">Initial value of the isActive property.</param>
        public static InfoMessage CreateInfoMessage(global::System.Int64 msgID, global::System.Int32 fromUserID, global::System.Int32 toUserID, global::System.DateTime createdDateTime, global::System.Byte msgTypeID, global::System.String visitorName, global::System.Boolean isUrgent, global::System.Byte msgStatusID, global::System.Boolean isActive)
        {
            InfoMessage infoMessage = new InfoMessage();
            infoMessage.msgID = msgID;
            infoMessage.FromUserID = fromUserID;
            infoMessage.ToUserID = toUserID;
            infoMessage.CreatedDateTime = createdDateTime;
            infoMessage.msgTypeID = msgTypeID;
            infoMessage.VisitorName = visitorName;
            infoMessage.isUrgent = isUrgent;
            infoMessage.msgStatusID = msgStatusID;
            infoMessage.isActive = isActive;
            return infoMessage;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 msgID
        {
            get
            {
                return _msgID;
            }
            set
            {
                if (_msgID != value)
                {
                    OnmsgIDChanging(value);
                    ReportPropertyChanging("msgID");
                    _msgID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("msgID");
                    OnmsgIDChanged();
                }
            }
        }
        private global::System.Int64 _msgID;
        partial void OnmsgIDChanging(global::System.Int64 value);
        partial void OnmsgIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TodayID
        {
            get
            {
                return _TodayID;
            }
            set
            {
                OnTodayIDChanging(value);
                ReportPropertyChanging("TodayID");
                _TodayID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TodayID");
                OnTodayIDChanged();
            }
        }
        private Nullable<global::System.Int32> _TodayID;
        partial void OnTodayIDChanging(Nullable<global::System.Int32> value);
        partial void OnTodayIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FromUserID
        {
            get
            {
                return _FromUserID;
            }
            set
            {
                OnFromUserIDChanging(value);
                ReportPropertyChanging("FromUserID");
                _FromUserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FromUserID");
                OnFromUserIDChanged();
            }
        }
        private global::System.Int32 _FromUserID;
        partial void OnFromUserIDChanging(global::System.Int32 value);
        partial void OnFromUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ToUserID
        {
            get
            {
                return _ToUserID;
            }
            set
            {
                OnToUserIDChanging(value);
                ReportPropertyChanging("ToUserID");
                _ToUserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ToUserID");
                OnToUserIDChanged();
            }
        }
        private global::System.Int32 _ToUserID;
        partial void OnToUserIDChanging(global::System.Int32 value);
        partial void OnToUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDateTime
        {
            get
            {
                return _CreatedDateTime;
            }
            set
            {
                OnCreatedDateTimeChanging(value);
                ReportPropertyChanging("CreatedDateTime");
                _CreatedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDateTime");
                OnCreatedDateTimeChanged();
            }
        }
        private global::System.DateTime _CreatedDateTime;
        partial void OnCreatedDateTimeChanging(global::System.DateTime value);
        partial void OnCreatedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte msgTypeID
        {
            get
            {
                return _msgTypeID;
            }
            set
            {
                OnmsgTypeIDChanging(value);
                ReportPropertyChanging("msgTypeID");
                _msgTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("msgTypeID");
                OnmsgTypeIDChanged();
            }
        }
        private global::System.Byte _msgTypeID;
        partial void OnmsgTypeIDChanging(global::System.Byte value);
        partial void OnmsgTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String VisitorName
        {
            get
            {
                return _VisitorName;
            }
            set
            {
                OnVisitorNameChanging(value);
                ReportPropertyChanging("VisitorName");
                _VisitorName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("VisitorName");
                OnVisitorNameChanged();
            }
        }
        private global::System.String _VisitorName;
        partial void OnVisitorNameChanging(global::System.String value);
        partial void OnVisitorNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VisitorMessage
        {
            get
            {
                return _VisitorMessage;
            }
            set
            {
                OnVisitorMessageChanging(value);
                ReportPropertyChanging("VisitorMessage");
                _VisitorMessage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VisitorMessage");
                OnVisitorMessageChanged();
            }
        }
        private global::System.String _VisitorMessage;
        partial void OnVisitorMessageChanging(global::System.String value);
        partial void OnVisitorMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean isUrgent
        {
            get
            {
                return _isUrgent;
            }
            set
            {
                OnisUrgentChanging(value);
                ReportPropertyChanging("isUrgent");
                _isUrgent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isUrgent");
                OnisUrgentChanged();
            }
        }
        private global::System.Boolean _isUrgent;
        partial void OnisUrgentChanging(global::System.Boolean value);
        partial void OnisUrgentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte msgStatusID
        {
            get
            {
                return _msgStatusID;
            }
            set
            {
                OnmsgStatusIDChanging(value);
                ReportPropertyChanging("msgStatusID");
                _msgStatusID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("msgStatusID");
                OnmsgStatusIDChanged();
            }
        }
        private global::System.Byte _msgStatusID;
        partial void OnmsgStatusIDChanging(global::System.Byte value);
        partial void OnmsgStatusIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean isActive
        {
            get
            {
                return _isActive;
            }
            set
            {
                OnisActiveChanging(value);
                ReportPropertyChanging("isActive");
                _isActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isActive");
                OnisActiveChanged();
            }
        }
        private global::System.Boolean _isActive;
        partial void OnisActiveChanging(global::System.Boolean value);
        partial void OnisActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ResponseString
        {
            get
            {
                return _ResponseString;
            }
            set
            {
                OnResponseStringChanging(value);
                ReportPropertyChanging("ResponseString");
                _ResponseString = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ResponseString");
                OnResponseStringChanged();
            }
        }
        private global::System.String _ResponseString;
        partial void OnResponseStringChanging(global::System.String value);
        partial void OnResponseStringChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ResponseTime
        {
            get
            {
                return _ResponseTime;
            }
            set
            {
                OnResponseTimeChanging(value);
                ReportPropertyChanging("ResponseTime");
                _ResponseTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ResponseTime");
                OnResponseTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _ResponseTime;
        partial void OnResponseTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnResponseTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Autotime
        {
            get
            {
                return _Autotime;
            }
            set
            {
                OnAutotimeChanging(value);
                ReportPropertyChanging("Autotime");
                _Autotime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Autotime");
                OnAutotimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _Autotime;
        partial void OnAutotimeChanging(Nullable<global::System.DateTime> value);
        partial void OnAutotimeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VisitorAPPModel", "FK_InfoUserFrom_InfoMessage", "InfoUser")]
        public InfoUser InfoUser
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<InfoUser>("VisitorAPPModel.FK_InfoUserFrom_InfoMessage", "InfoUser").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<InfoUser>("VisitorAPPModel.FK_InfoUserFrom_InfoMessage", "InfoUser").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<InfoUser> InfoUserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<InfoUser>("VisitorAPPModel.FK_InfoUserFrom_InfoMessage", "InfoUser");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<InfoUser>("VisitorAPPModel.FK_InfoUserFrom_InfoMessage", "InfoUser", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VisitorAPPModel", "FK_InfoUserTo_InfoMessage", "InfoUser")]
        public InfoUser InfoUser1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<InfoUser>("VisitorAPPModel.FK_InfoUserTo_InfoMessage", "InfoUser").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<InfoUser>("VisitorAPPModel.FK_InfoUserTo_InfoMessage", "InfoUser").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<InfoUser> InfoUser1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<InfoUser>("VisitorAPPModel.FK_InfoUserTo_InfoMessage", "InfoUser");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<InfoUser>("VisitorAPPModel.FK_InfoUserTo_InfoMessage", "InfoUser", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VisitorAPPModel", "FK_TypeMsgContent_InfoMessage", "TypeMsgContent")]
        public TypeMsgContent TypeMsgContent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TypeMsgContent>("VisitorAPPModel.FK_TypeMsgContent_InfoMessage", "TypeMsgContent").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TypeMsgContent>("VisitorAPPModel.FK_TypeMsgContent_InfoMessage", "TypeMsgContent").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TypeMsgContent> TypeMsgContentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TypeMsgContent>("VisitorAPPModel.FK_TypeMsgContent_InfoMessage", "TypeMsgContent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TypeMsgContent>("VisitorAPPModel.FK_TypeMsgContent_InfoMessage", "TypeMsgContent", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VisitorAPPModel", "FK_TypeMsgStatus_msgStatus", "TypeMsgStatu")]
        public TypeMsgStatu TypeMsgStatu
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TypeMsgStatu>("VisitorAPPModel.FK_TypeMsgStatus_msgStatus", "TypeMsgStatu").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TypeMsgStatu>("VisitorAPPModel.FK_TypeMsgStatus_msgStatus", "TypeMsgStatu").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TypeMsgStatu> TypeMsgStatuReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TypeMsgStatu>("VisitorAPPModel.FK_TypeMsgStatus_msgStatus", "TypeMsgStatu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TypeMsgStatu>("VisitorAPPModel.FK_TypeMsgStatus_msgStatus", "TypeMsgStatu", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VisitorAPPModel", Name="InfoUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class InfoUser : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new InfoUser object.
        /// </summary>
        /// <param name="uID">Initial value of the UID property.</param>
        /// <param name="userRoleID">Initial value of the UserRoleID property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="isActive">Initial value of the isActive property.</param>
        public static InfoUser CreateInfoUser(global::System.Int32 uID, global::System.Byte userRoleID, global::System.String username, global::System.String password, global::System.String name, global::System.Boolean isActive)
        {
            InfoUser infoUser = new InfoUser();
            infoUser.UID = uID;
            infoUser.UserRoleID = userRoleID;
            infoUser.Username = username;
            infoUser.Password = password;
            infoUser.Name = name;
            infoUser.isActive = isActive;
            return infoUser;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UID
        {
            get
            {
                return _UID;
            }
            set
            {
                if (_UID != value)
                {
                    OnUIDChanging(value);
                    ReportPropertyChanging("UID");
                    _UID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UID");
                    OnUIDChanged();
                }
            }
        }
        private global::System.Int32 _UID;
        partial void OnUIDChanging(global::System.Int32 value);
        partial void OnUIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte UserRoleID
        {
            get
            {
                return _UserRoleID;
            }
            set
            {
                OnUserRoleIDChanging(value);
                ReportPropertyChanging("UserRoleID");
                _UserRoleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserRoleID");
                OnUserRoleIDChanged();
            }
        }
        private global::System.Byte _UserRoleID;
        partial void OnUserRoleIDChanging(global::System.Byte value);
        partial void OnUserRoleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MobileNo
        {
            get
            {
                return _MobileNo;
            }
            set
            {
                OnMobileNoChanging(value);
                ReportPropertyChanging("MobileNo");
                _MobileNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MobileNo");
                OnMobileNoChanged();
            }
        }
        private global::System.String _MobileNo;
        partial void OnMobileNoChanging(global::System.String value);
        partial void OnMobileNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailID
        {
            get
            {
                return _EmailID;
            }
            set
            {
                OnEmailIDChanging(value);
                ReportPropertyChanging("EmailID");
                _EmailID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmailID");
                OnEmailIDChanged();
            }
        }
        private global::System.String _EmailID;
        partial void OnEmailIDChanging(global::System.String value);
        partial void OnEmailIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SystemIDAddress
        {
            get
            {
                return _SystemIDAddress;
            }
            set
            {
                OnSystemIDAddressChanging(value);
                ReportPropertyChanging("SystemIDAddress");
                _SystemIDAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SystemIDAddress");
                OnSystemIDAddressChanged();
            }
        }
        private global::System.String _SystemIDAddress;
        partial void OnSystemIDAddressChanging(global::System.String value);
        partial void OnSystemIDAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MobileIMENo
        {
            get
            {
                return _MobileIMENo;
            }
            set
            {
                OnMobileIMENoChanging(value);
                ReportPropertyChanging("MobileIMENo");
                _MobileIMENo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MobileIMENo");
                OnMobileIMENoChanged();
            }
        }
        private global::System.String _MobileIMENo;
        partial void OnMobileIMENoChanging(global::System.String value);
        partial void OnMobileIMENoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean isActive
        {
            get
            {
                return _isActive;
            }
            set
            {
                OnisActiveChanging(value);
                ReportPropertyChanging("isActive");
                _isActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isActive");
                OnisActiveChanged();
            }
        }
        private global::System.Boolean _isActive;
        partial void OnisActiveChanging(global::System.Boolean value);
        partial void OnisActiveChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VisitorAPPModel", "FK_InfoUser_TypeUserRole", "TypeUserRole")]
        public TypeUserRole TypeUserRole
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TypeUserRole>("VisitorAPPModel.FK_InfoUser_TypeUserRole", "TypeUserRole").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TypeUserRole>("VisitorAPPModel.FK_InfoUser_TypeUserRole", "TypeUserRole").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TypeUserRole> TypeUserRoleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TypeUserRole>("VisitorAPPModel.FK_InfoUser_TypeUserRole", "TypeUserRole");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TypeUserRole>("VisitorAPPModel.FK_InfoUser_TypeUserRole", "TypeUserRole", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VisitorAPPModel", "FK_InfoUserFrom_InfoMessage", "InfoMessage")]
        public EntityCollection<InfoMessage> InfoMessages
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<InfoMessage>("VisitorAPPModel.FK_InfoUserFrom_InfoMessage", "InfoMessage");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<InfoMessage>("VisitorAPPModel.FK_InfoUserFrom_InfoMessage", "InfoMessage", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VisitorAPPModel", "FK_InfoUserTo_InfoMessage", "InfoMessage")]
        public EntityCollection<InfoMessage> InfoMessages1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<InfoMessage>("VisitorAPPModel.FK_InfoUserTo_InfoMessage", "InfoMessage");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<InfoMessage>("VisitorAPPModel.FK_InfoUserTo_InfoMessage", "InfoMessage", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VisitorAPPModel", Name="SettingsForm")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SettingsForm : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SettingsForm object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static SettingsForm CreateSettingsForm(global::System.Int32 id)
        {
            SettingsForm settingsForm = new SettingsForm();
            settingsForm.Id = id;
            return settingsForm;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private Nullable<global::System.Int32> _UserID;
        partial void OnUserIDChanging(Nullable<global::System.Int32> value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SettingsName
        {
            get
            {
                return _SettingsName;
            }
            set
            {
                OnSettingsNameChanging(value);
                ReportPropertyChanging("SettingsName");
                _SettingsName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SettingsName");
                OnSettingsNameChanged();
            }
        }
        private global::System.String _SettingsName;
        partial void OnSettingsNameChanging(global::System.String value);
        partial void OnSettingsNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Enable
        {
            get
            {
                return _Enable;
            }
            set
            {
                OnEnableChanging(value);
                ReportPropertyChanging("Enable");
                _Enable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Enable");
                OnEnableChanged();
            }
        }
        private Nullable<global::System.Boolean> _Enable;
        partial void OnEnableChanging(Nullable<global::System.Boolean> value);
        partial void OnEnableChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VisitorAPPModel", Name="TypeMsgContent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TypeMsgContent : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TypeMsgContent object.
        /// </summary>
        /// <param name="msgTypeId">Initial value of the MsgTypeId property.</param>
        /// <param name="messageContent">Initial value of the MessageContent property.</param>
        /// <param name="isActive">Initial value of the isActive property.</param>
        public static TypeMsgContent CreateTypeMsgContent(global::System.Byte msgTypeId, global::System.String messageContent, global::System.Boolean isActive)
        {
            TypeMsgContent typeMsgContent = new TypeMsgContent();
            typeMsgContent.MsgTypeId = msgTypeId;
            typeMsgContent.MessageContent = messageContent;
            typeMsgContent.isActive = isActive;
            return typeMsgContent;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte MsgTypeId
        {
            get
            {
                return _MsgTypeId;
            }
            set
            {
                if (_MsgTypeId != value)
                {
                    OnMsgTypeIdChanging(value);
                    ReportPropertyChanging("MsgTypeId");
                    _MsgTypeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MsgTypeId");
                    OnMsgTypeIdChanged();
                }
            }
        }
        private global::System.Byte _MsgTypeId;
        partial void OnMsgTypeIdChanging(global::System.Byte value);
        partial void OnMsgTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MessageContent
        {
            get
            {
                return _MessageContent;
            }
            set
            {
                OnMessageContentChanging(value);
                ReportPropertyChanging("MessageContent");
                _MessageContent = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MessageContent");
                OnMessageContentChanged();
            }
        }
        private global::System.String _MessageContent;
        partial void OnMessageContentChanging(global::System.String value);
        partial void OnMessageContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean isActive
        {
            get
            {
                return _isActive;
            }
            set
            {
                OnisActiveChanging(value);
                ReportPropertyChanging("isActive");
                _isActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isActive");
                OnisActiveChanged();
            }
        }
        private global::System.Boolean _isActive;
        partial void OnisActiveChanging(global::System.Boolean value);
        partial void OnisActiveChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VisitorAPPModel", "FK_TypeMsgContent_InfoMessage", "InfoMessage")]
        public EntityCollection<InfoMessage> InfoMessages
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<InfoMessage>("VisitorAPPModel.FK_TypeMsgContent_InfoMessage", "InfoMessage");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<InfoMessage>("VisitorAPPModel.FK_TypeMsgContent_InfoMessage", "InfoMessage", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VisitorAPPModel", Name="TypeMsgStatu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TypeMsgStatu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TypeMsgStatu object.
        /// </summary>
        /// <param name="msgStatusID">Initial value of the msgStatusID property.</param>
        /// <param name="msgStatusDesc">Initial value of the msgStatusDesc property.</param>
        /// <param name="isActive">Initial value of the isActive property.</param>
        public static TypeMsgStatu CreateTypeMsgStatu(global::System.Byte msgStatusID, global::System.String msgStatusDesc, global::System.Boolean isActive)
        {
            TypeMsgStatu typeMsgStatu = new TypeMsgStatu();
            typeMsgStatu.msgStatusID = msgStatusID;
            typeMsgStatu.msgStatusDesc = msgStatusDesc;
            typeMsgStatu.isActive = isActive;
            return typeMsgStatu;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte msgStatusID
        {
            get
            {
                return _msgStatusID;
            }
            set
            {
                if (_msgStatusID != value)
                {
                    OnmsgStatusIDChanging(value);
                    ReportPropertyChanging("msgStatusID");
                    _msgStatusID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("msgStatusID");
                    OnmsgStatusIDChanged();
                }
            }
        }
        private global::System.Byte _msgStatusID;
        partial void OnmsgStatusIDChanging(global::System.Byte value);
        partial void OnmsgStatusIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String msgStatusDesc
        {
            get
            {
                return _msgStatusDesc;
            }
            set
            {
                OnmsgStatusDescChanging(value);
                ReportPropertyChanging("msgStatusDesc");
                _msgStatusDesc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("msgStatusDesc");
                OnmsgStatusDescChanged();
            }
        }
        private global::System.String _msgStatusDesc;
        partial void OnmsgStatusDescChanging(global::System.String value);
        partial void OnmsgStatusDescChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean isActive
        {
            get
            {
                return _isActive;
            }
            set
            {
                OnisActiveChanging(value);
                ReportPropertyChanging("isActive");
                _isActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isActive");
                OnisActiveChanged();
            }
        }
        private global::System.Boolean _isActive;
        partial void OnisActiveChanging(global::System.Boolean value);
        partial void OnisActiveChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VisitorAPPModel", "FK_TypeMsgStatus_msgStatus", "InfoMessage")]
        public EntityCollection<InfoMessage> InfoMessages
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<InfoMessage>("VisitorAPPModel.FK_TypeMsgStatus_msgStatus", "InfoMessage");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<InfoMessage>("VisitorAPPModel.FK_TypeMsgStatus_msgStatus", "InfoMessage", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VisitorAPPModel", Name="TypeUserRole")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TypeUserRole : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TypeUserRole object.
        /// </summary>
        /// <param name="userRoleID">Initial value of the UserRoleID property.</param>
        /// <param name="userRoleDesc">Initial value of the UserRoleDesc property.</param>
        /// <param name="isActive">Initial value of the isActive property.</param>
        public static TypeUserRole CreateTypeUserRole(global::System.Byte userRoleID, global::System.String userRoleDesc, global::System.Boolean isActive)
        {
            TypeUserRole typeUserRole = new TypeUserRole();
            typeUserRole.UserRoleID = userRoleID;
            typeUserRole.UserRoleDesc = userRoleDesc;
            typeUserRole.isActive = isActive;
            return typeUserRole;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte UserRoleID
        {
            get
            {
                return _UserRoleID;
            }
            set
            {
                if (_UserRoleID != value)
                {
                    OnUserRoleIDChanging(value);
                    ReportPropertyChanging("UserRoleID");
                    _UserRoleID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserRoleID");
                    OnUserRoleIDChanged();
                }
            }
        }
        private global::System.Byte _UserRoleID;
        partial void OnUserRoleIDChanging(global::System.Byte value);
        partial void OnUserRoleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserRoleDesc
        {
            get
            {
                return _UserRoleDesc;
            }
            set
            {
                OnUserRoleDescChanging(value);
                ReportPropertyChanging("UserRoleDesc");
                _UserRoleDesc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserRoleDesc");
                OnUserRoleDescChanged();
            }
        }
        private global::System.String _UserRoleDesc;
        partial void OnUserRoleDescChanging(global::System.String value);
        partial void OnUserRoleDescChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean isActive
        {
            get
            {
                return _isActive;
            }
            set
            {
                OnisActiveChanging(value);
                ReportPropertyChanging("isActive");
                _isActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isActive");
                OnisActiveChanged();
            }
        }
        private global::System.Boolean _isActive;
        partial void OnisActiveChanging(global::System.Boolean value);
        partial void OnisActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserMenuAccess
        {
            get
            {
                return _UserMenuAccess;
            }
            set
            {
                OnUserMenuAccessChanging(value);
                ReportPropertyChanging("UserMenuAccess");
                _UserMenuAccess = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserMenuAccess");
                OnUserMenuAccessChanged();
            }
        }
        private global::System.String _UserMenuAccess;
        partial void OnUserMenuAccessChanging(global::System.String value);
        partial void OnUserMenuAccessChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VisitorAPPModel", "FK_InfoUser_TypeUserRole", "InfoUser")]
        public EntityCollection<InfoUser> InfoUsers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<InfoUser>("VisitorAPPModel.FK_InfoUser_TypeUserRole", "InfoUser");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<InfoUser>("VisitorAPPModel.FK_InfoUser_TypeUserRole", "InfoUser", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
